name: "CI"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v15
      - uses: cachix/cachix-action@v10
        with:
          name: welteki
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          skipPush: true
      - name: Build faasd 🔧
        run: |
          nix build -L .#faasd
          nix eval --json .#faasd | jq -r | cachix push welteki
      - name: Build containerd 🔧
        run: |
          nix build -L .#faasd-containerd
          nix eval --json .#faasd-containerd | jq -r | cachix push welteki
      - name: Build cni-plugin 🔧
        run: |
          nix build -L .#faasd-cni-plugins
          nix eval --json .#faasd-cni-plugins | jq -r | cachix push welteki
      - name: Build OpenFaaS core images 🔧
        run: |
          nix build .#basic-auth-image \
            .#gateway-image \
            .#queue-worker-image \
            .#nats-image \
            .#prometheus-image
